# docker-compose.yml
version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    command: python src/bot/main.py
    environment:
      - DATABASE_URL=postgresql+asyncpg://botuser:botpass@postgres:5432/botdb
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - postgres

volumes:
  pgdata:
